#!/bin/bash

# Test-dataset-2 Reference

python sequence_labelling/metrics_full_correlated.py datasets/TED_2/4classes_capt/data.capt.ndp.test.lab ~/data/seq_labelling_logs/caps_4cl3_rnn512_gru_bat64_layer2_drop0p5/test_predictions_task0.tsv

python sequence_labelling/metrics_full_correlated.py datasets/TED_2/4classes_punct/data.ndp.test.lab ~/data/seq_labelling_logs/punc7_4cl_rnn256_gru_bat64_layer1/test_predictions_task0.tsv

python sequence_labelling/metrics_full_correlated.py datasets/TED_2/4classes_capt/data.capt.ndp.test.lab ~/data/seq_labelling_logs/caps7_4cl_rnn512_gru_bat64_layer2_drop0p75/test_predictions_task0.tsv

python sequence_labelling/metrics_full_correlated.py datasets/TED_2/4classes_punct/data.ndp.test.lab ~/data/seq_labelling_logs/punc_4cl_rnn512_lstm_hid1_hdim300_linear_bat64_layer1/test_predictions_task0.tsv

python sequence_labelling/metrics_full_correlated.py datasets/TED_2/4classes/data.ndp.test.lab ~/data/seq_labelling_logs/corr_4cl3_rnn256_lstm_hid1_hdim300_linear_wt0p9_bat64_layer1/test_predictions_task0.tsv ~/data/seq_labelling_logs/corr_4cl3_rnn256_lstm_hid1_hdim300_linear_wt0p9_bat64_layer1/test_predictions_task1.tsv

python sequence_labelling/metrics_full_correlated.py datasets/TED_2/4classes/data.ndp.test.lab ~/data/seq_labelling_logs/corr_4cl3_rnn512_lstm_hid1_hdim300_linear_wt0p75_bat64_layer2_drop1p0/test_predictions_task0.tsv ~/data/seq_labelling_logs/corr_4cl3_rnn512_lstm_hid1_hdim300_linear_wt0p75_bat64_layer2_drop1p0/test_predictions_task1.tsv

python sequence_labelling/metrics_full_correlated.py datasets/TED_2/4classes/data.ndp.test.lab ~/data/seq_labelling_logs/corr7_4cl_rnn512_gru_hid1_hdim300_relu_wt0p9_bat64_layer2_drop0p5/test_predictions_task0.tsv ~/data/seq_labelling_logs/corr7_4cl_rnn512_gru_hid1_hdim300_relu_wt0p9_bat64_layer2_drop0p5/test_predictions_task1.tsv

python sequence_labelling/metrics_full_correlated.py datasets/TED_2/4classes/data.ndp.test.lab ~/data/seq_labelling_logs/corr7_4cl_rnn512_lstm_hid1_hdim300_relu_wt0p75_bat64_layer1_drop0p75/test_predictions_task0.tsv ~/data/seq_labelling_logs/corr7_4cl_rnn512_lstm_hid1_hdim300_relu_wt0p75_bat64_layer1_drop0p75/test_predictions_task1.tsv

# Test-dataset-1 Reference

python sequence_labelling/metrics_full_correlated.py datasets/TED_3/4classes_capt/data.capt.ndp.test.lab ~/data/seq_labelling_logs/caps_4cl3_rnn512_gru_bat64_layer2_drop0p5/test_ted3_task0.tsv

python sequence_labelling/metrics_full_correlated.py datasets/TED_3/4classes_punct/data.ndp.test.lab ~/data/seq_labelling_logs/punc7_4cl_rnn256_gru_bat64_layer1/test_ted3_task0.tsv

python sequence_labelling/metrics_full_correlated.py datasets/TED_3/4classes_capt/data.capt.ndp.test.lab ~/data/seq_labelling_logs/caps7_4cl_rnn512_gru_bat64_layer2_drop0p75/test_ted3_task0.tsv

python sequence_labelling/metrics_full_correlated.py datasets/TED_3/4classes_punct/data.ndp.test.lab ~/data/seq_labelling_logs/punc_4cl_rnn512_lstm_hid1_hdim300_linear_bat64_layer1/test_ted3_task0.tsv

python sequence_labelling/metrics_full_correlated.py datasets/TED_3/4classes/data.ndp.test.lab ~/data/seq_labelling_logs/corr_4cl3_rnn256_lstm_hid1_hdim300_linear_wt0p9_bat64_layer1/test_ted3_task0.tsv ~/data/seq_labelling_logs/corr_4cl3_rnn256_lstm_hid1_hdim300_linear_wt0p9_bat64_layer1/test_ted3_task1.tsv

python sequence_labelling/metrics_full_correlated.py datasets/TED_3/4classes/data.ndp.test.lab ~/data/seq_labelling_logs/corr_4cl3_rnn512_lstm_hid1_hdim300_linear_wt0p75_bat64_layer2_drop1p0/test_ted3_task0.tsv ~/data/seq_labelling_logs/corr_4cl3_rnn512_lstm_hid1_hdim300_linear_wt0p75_bat64_layer2_drop1p0/test_ted3_task1.tsv

python sequence_labelling/metrics_full_correlated.py datasets/TED_3/4classes/data.ndp.test.lab ~/data/seq_labelling_logs/corr7_4cl_rnn512_gru_hid1_hdim300_relu_wt0p9_bat64_layer2_drop0p5/test_ted3_task0.tsv ~/data/seq_labelling_logs/corr7_4cl_rnn512_gru_hid1_hdim300_relu_wt0p9_bat64_layer2_drop0p5/test_ted3_task1.tsv

python sequence_labelling/metrics_full_correlated.py datasets/TED_3/4classes/data.ndp.test.lab ~/data/seq_labelling_logs/corr7_4cl_rnn512_lstm_hid1_hdim300_relu_wt0p75_bat64_layer1_drop0p75/test_ted3_task0.tsv ~/data/seq_labelling_logs/corr7_4cl_rnn512_lstm_hid1_hdim300_relu_wt0p75_bat64_layer1_drop0p75/test_ted3_task1.tsv


# Test-dataset-2 ASR

python sequence_labelling/metrics_full_correlated.py datasets/TED_2/4classes_capt/data.capt.ndp.test.lab datasets/TED_2_ASR/ted2_asr_punct_slots.txt ~/data/seq_labelling_logs/caps_4cl3_rnn512_gru_bat64_layer2_drop0p5/test_ted2_asr_task0.tsv

python sequence_labelling/metrics_full_correlated.py datasets/TED_2/4classes_punct/data.ndp.test.lab datasets/TED_2_ASR/ted2_asr_punct_slots.txt ~/data/seq_labelling_logs/punc7_4cl_rnn256_gru_bat64_layer1/test_ted2_asr_task0.tsv

python sequence_labelling/metrics_full_correlated.py datasets/TED_2/4classes_capt/data.capt.ndp.test.lab datasets/TED_2_ASR/ted2_asr_punct_slots.txt ~/data/seq_labelling_logs/caps7_4cl_rnn512_gru_bat64_layer2_drop0p75/test_ted2_asr_task0.tsv

python sequence_labelling/metrics_full_correlated.py datasets/TED_2/4classes_punct/data.ndp.test.lab datasets/TED_2_ASR/ted2_asr_punct_slots.txt ~/data/seq_labelling_logs/punc_4cl_rnn512_lstm_hid1_hdim300_linear_bat64_layer1/test_ted2_asr_task0.tsv

python sequence_labelling/metrics_full_correlated.py datasets/TED_2/4classes/data.ndp.test.lab datasets/TED_2_ASR/ted2_asr_punct_slots.txt ~/data/seq_labelling_logs/corr_4cl3_rnn256_lstm_hid1_hdim300_linear_wt0p9_bat64_layer1/test_ted2_asr_task0.tsv ~/data/seq_labelling_logs/corr_4cl3_rnn256_lstm_hid1_hdim300_linear_wt0p9_bat64_layer1/test_ted2_asr_task1.tsv

python sequence_labelling/metrics_full_correlated.py datasets/TED_2/4classes/data.ndp.test.lab datasets/TED_2_ASR/ted2_asr_punct_slots.txt ~/data/seq_labelling_logs/corr_4cl3_rnn512_lstm_hid1_hdim300_linear_wt0p75_bat64_layer2_drop1p0/test_ted2_asr_task0.tsv ~/data/seq_labelling_logs/corr_4cl3_rnn512_lstm_hid1_hdim300_linear_wt0p75_bat64_layer2_drop1p0/test_ted2_asr_task1.tsv

python sequence_labelling/metrics_full_correlated.py datasets/TED_2/4classes/data.ndp.test.lab datasets/TED_2_ASR/ted2_asr_punct_slots.txt ~/data/seq_labelling_logs/corr7_4cl_rnn512_gru_hid1_hdim300_relu_wt0p9_bat64_layer2_drop0p5/test_ted2_asr_task0.tsv ~/data/seq_labelling_logs/corr7_4cl_rnn512_gru_hid1_hdim300_relu_wt0p9_bat64_layer2_drop0p5/test_ted2_asr_task1.tsv

python sequence_labelling/metrics_full_correlated.py datasets/TED_2/4classes/data.ndp.test.lab datasets/TED_2_ASR/ted2_asr_punct_slots.txt ~/data/seq_labelling_logs/corr7_4cl_rnn512_lstm_hid1_hdim300_relu_wt0p75_bat64_layer1_drop0p75/test_ted2_asr_task0.tsv ~/data/seq_labelling_logs/corr7_4cl_rnn512_lstm_hid1_hdim300_relu_wt0p75_bat64_layer1_drop0p75/test_ted2_asr_task1.tsv


# Test-dataset-3 ASR

python sequence_labelling/metrics_full_correlated.py datasets/TED_3/4classes_capt/data.capt.ndp.test.lab datasets/TED_3_ASR/ted3_asr_punct_slots.txt ~/data/seq_labelling_logs/caps_4cl3_rnn512_gru_bat64_layer2_drop0p5/test_ted3_asr_task0.tsv

python sequence_labelling/metrics_full_correlated.py datasets/TED_3/4classes_punct/data.ndp.test.lab datasets/TED_3_ASR/ted3_asr_punct_slots.txt ~/data/seq_labelling_logs/punc7_4cl_rnn256_gru_bat64_layer1/test_ted3_asr_task0.tsv

python sequence_labelling/metrics_full_correlated.py datasets/TED_3/4classes_capt/data.capt.ndp.test.lab datasets/TED_3_ASR/ted3_asr_punct_slots.txt ~/data/seq_labelling_logs/caps7_4cl_rnn512_gru_bat64_layer2_drop0p75/test_ted3_asr_task0.tsv

python sequence_labelling/metrics_full_correlated.py datasets/TED_3/4classes_punct/data.ndp.test.lab datasets/TED_3_ASR/ted3_asr_punct_slots.txt ~/data/seq_labelling_logs/punc_4cl_rnn512_lstm_hid1_hdim300_linear_bat64_layer1/test_ted3_asr_task0.tsv

python sequence_labelling/metrics_full_correlated.py datasets/TED_3/4classes/data.ndp.test.lab datasets/TED_3_ASR/ted3_asr_punct_slots.txt ~/data/seq_labelling_logs/corr_4cl3_rnn256_lstm_hid1_hdim300_linear_wt0p9_bat64_layer1/test_ted3_asr_task0.tsv ~/data/seq_labelling_logs/corr_4cl3_rnn256_lstm_hid1_hdim300_linear_wt0p9_bat64_layer1/test_ted3_asr_task1.tsv

python sequence_labelling/metrics_full_correlated.py datasets/TED_3/4classes/data.ndp.test.lab datasets/TED_3_ASR/ted3_asr_punct_slots.txt ~/data/seq_labelling_logs/corr_4cl3_rnn512_lstm_hid1_hdim300_linear_wt0p75_bat64_layer2_drop1p0/test_ted3_asr_task0.tsv ~/data/seq_labelling_logs/corr_4cl3_rnn512_lstm_hid1_hdim300_linear_wt0p75_bat64_layer2_drop1p0/test_ted3_asr_task1.tsv

python sequence_labelling/metrics_full_correlated.py datasets/TED_3/4classes/data.ndp.test.lab datasets/TED_3_ASR/ted3_asr_punct_slots.txt ~/data/seq_labelling_logs/corr7_4cl_rnn512_gru_hid1_hdim300_relu_wt0p9_bat64_layer2_drop0p5/test_ted3_asr_task0.tsv ~/data/seq_labelling_logs/corr7_4cl_rnn512_gru_hid1_hdim300_relu_wt0p9_bat64_layer2_drop0p5/test_ted3_asr_task1.tsv

python sequence_labelling/metrics_full_correlated.py datasets/TED_3/4classes/data.ndp.test.lab datasets/TED_3_ASR/ted3_asr_punct_slots.txt ~/data/seq_labelling_logs/corr7_4cl_rnn512_lstm_hid1_hdim300_relu_wt0p75_bat64_layer1_drop0p75/test_ted3_asr_task0.tsv ~/data/seq_labelling_logs/corr7_4cl_rnn512_lstm_hid1_hdim300_relu_wt0p75_bat64_layer1_drop0p75/test_ted3_asr_task1.tsv

